version: '2'
services:

  redis:
    image: redis

  elasticsearch:
    image: elasticsearch

  app:
    environment:
      - REDIS_HOST=redis
      - ES_HOST=elasticserch:9200
    build:
      context: .
    volumes:
      - ./src:/code/src
    ports:
      - 3000:3000
    depends_on:
      - redis
      - elasticsearch
