version: '3'
services:

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  app:
    environment:
      - REDIS_HOST=redis
      - ES_HOST=elasticsearch:9200
      - DB_HOSTNAME=db
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
    ports:
      - 3000:3000
    build:
      context: .
    volumes:
      - ./src:/code/src
    depends_on:
      - db
      - redis
      - elasticsearch
    links:
      - db
      - redis
      - elasticsearch
    entrypoint: src/commands/wait-for-it.sh -t 120 elasticsearch:9200 -- ./entrypoint.sh
