version: '2'
services:

  redis:
    image: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  app:
    environment:
      - REDIS_HOST=redis
      - ES_HOST=http://elastic:changeme@elasticsearch:9200
    build:
      context: .
    volumes:
      - ./src:/code/src
    ports:
      - 3000:3000
    depends_on:
      - redis
      - elasticsearch
    entrypoint: src/commands/wait-for-it.sh -t 120 elasticsearch:9200 -- npm run start:dev
