FROM python:3.6
RUN mkdir /code
WORKDIR /code
ADD . /code/
RUN pip install -r requirements.txt
ENV DJANGO_SETTINGS_MODULE=docnow.settings
ENV PYTHONPATH=/code:$PYTHONPATH
CMD ["/bin/bash", "-c", "sleep 10; django-admin migrate; django-admin runserver 0.0.0.0:8000"]
