version: '2'
services:
  db:
    image: postgres
  webpack:
    build:
      context: .
      dockerfile: dockerfile.webpack
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    command: bash -c "npm run start"
  web:
    build:
      context: .
      dockerfile: dockerfile.django
    command: bash -c "python3 ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
