version: '2'
services:

  redis:
    image: redis

  db:
    image: postgres

  webpack:
    build:
      context: .
      dockerfile: dockerfile.webpack
    volumes:
      - .:/code
    ports:
      - "3000:3000"

  django:
    build:
      context: .
      dockerfile: dockerfile.django
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - webpack

  trends:
    build:
      context: .
      dockerfile: dockerfile.django
    volumes:
      - .:/code
    depends_on:
      - django
      - db
    entrypoint: ["django-admin", "trends"]
