version: '2'
services:

  redis:
    image: redis

  elasticsearch:
    image: elasticsearch

  app:
    environment:
      - REDIS_HOST=redis
      - ES_HOST=elasticsearch:9200
    build:
      context: .
    volumes:
      - ./src:/code/src
    ports:
      - 3000:3000
    depends_on:
      - redis
      - elasticsearch
    entrypoint: src/commands/wait-for-it.sh -t 120 elasticsearch:9200 -- npm run start
