version: '3'
services:

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"

  app:
    environment:
      - REDIS_HOST=redis
      - DB_HOSTNAME=db
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
    ports:
      - 3000:3000
    build:
      context: .
    volumes:
      - ./src:/code/src
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    entrypoint: src/commands/wait-for-it.sh -t 120 db:5432 -- ./entrypoint.sh
