site_name: docnow 
site_url: https://readthedocs.org/projects/docnow/
site_description: A Twitter data collection and appraisal tool.

repo_url: https://github.com/docnow/docnow
repo_name: docnow
edit_uri: edit/main/docs/

theme:
  name: "material"
  logo: images/docnow.png
  palette:
    scheme: preference
  features:
    - navigation.expand
    - navigation.indexes

nav: 
  - Introduction: index.md
  - Run Locally: local.md
  - Run in the Cloud:
    - Overview: cloud/index.md
    - AWS: cloud/aws.md
    - Digital Ocean: cloud/digital-ocean.md
    - Scaleway: cloud/scaleway.md
  - Troubleshooting: troubleshooting.md
  - API: api.md
  - Database: db.md

plugins:
- search

markdown_extensions:
