site_name: docnow 
site_url: https://readthedocs.org/projects/docnow/
site_description: A Twitter data collection and appraisal tool.

repo_url: https://github.com/docnow/docnow
repo_name: docnow
edit_uri: edit/main/docs/

theme:
  name: "material"
  logo: images/docnow.png
  palette:
    scheme: preference
  features:
    - navigation.expand
    - navigation.indexes

nav: 
  - Introduction: index.md
  - Run Locally:
    - Overview: local/index.md
    - Centos: local/centOSREADME.md
    - macOS: local/macOSREADME.md
    - Ubuntu: local/ubuntuREADME.md
    - Microsoft Windows: local/mswinOSREADME.md
  - Run in the Cloud:
    - Overview: cloud/index.md
    - AWS: cloud/aws.md
    - Digital Ocean: cloud/digital-ocean.md
    - Google Cloud Platform: cloud/google.md
    - Linode: cloud/linode.md
    - Scaleway: cloud/scaleway.md
  - Troubleshooting: troubleshooting.md
  - API: api.md
  - Database: db.md
  - Docnow App Configuration: configuration.md

plugins:
- search

markdown_extensions:
