name: DocNow Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout git repository
        uses: actions/checkout@v2

      - name: run tests in docker
        env:
          DB_HOSTNAME: db
          DB_USERNAME: docnow
          DB_PASSWORD: docnow
          DB_DATABASE: docnow_dev
          NODE_ENV: test
          CONSUMER_KEY: ${{ secrets.consumer_key }}
          CONSUMER_SECRET: ${{ secrets.consumer_secret }}
          ACCESS_TOKEN: ${{ secrets.access_token }}
          ACCESS_TOKEN_SECRET: ${{ secrets.access_token_secret }}
        run: docker-compose up --build --exit-code-from app
