name: DocNow Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout git repository
        uses: actions/checkout@v2

      - name: run tests in docker
        env:
          DB_HOSTNAME: db
          DB_USERNAME: docnow
          DB_PASSWORD: docnow
          DB_DATABASE: docnow_dev
          NODE_ENV: test
          CONSUMER_KEY: ${{ secrets.consumer_key }}
          CONSUMER_SECRET: ${{ secrets.consumer_secret }}
          ACCESS_TOKEN: ${{ secrets.access_token }}
          ACCESS_TOKEN_SECRET: ${{ secrets.access_token_secret }}
        run: docker-compose up --build --exit-code-from app

      - name: notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: development
          status: SUCCESS
          color: good

      - name: notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: development
          status: FAILED
          color: danger
